services:
  # --- DATABASE SERVICE ---
  postgres:
    image: postgres:15-alpine
    container_name: eclass_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eclass_network

  # --- NEXT.JS APP SERVICE ---
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eclass_app
    restart: always
    ports:
      - "3000:3000"
    # Chỉ cần mục này là nó tự động nạp TẤT CẢ các biến trong .env vào app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - eclass_network

volumes:
  postgres_data:
    driver: local

networks:
  eclass_network:
    driver: bridge
