version: "3.8"

services:
  # 1. DATABASE
  postgres:
    image: postgres:15-alpine
    container_name: eclass_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eclass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


  # 3. WEB APP (Đây là chỗ để nó gọi Dockerfile của bạn)
  app:
    build: . # Nó sẽ tìm file Dockerfile trong cùng thư mục để build
    container_name: eclass_app
    ports:
      - "3000:3000"
    env_file: .env # Nó sẽ đọc các biến Bunny/DB từ file .env
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
