version: "3.8"

services:
  # 1. DATABASE
  postgres:
    image: postgres:15-alpine
    container_name: eclass_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # Đảm bảo khớp với DATABASE_URL trong .env
      POSTGRES_DB: eclass
    ports:
      - "5433:5432" # Máy thật dùng 5433, bên trong Docker dùng 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. WEB APP
  app:
    build: .
    container_name: eclass_app
    ports:
      - "3000:3000"
    env_file: .env # Docker sẽ nạp các biến từ file .env vào đây
    depends_on:
      - postgres # Đợi Database khởi động xong mới chạy App
    restart: always

volumes:
  postgres_data:
